//version "3.2.0"

#include "zscript/mechanics/m8f_hn/m8f_hn_AreaNameMarkerExample.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_AreaNameSources.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_AutoSwitch.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Data.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_EntrywayTranslocator.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_SpaceTunnelingDevice.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_EventHandler.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Footsteps.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_UseMark.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Pointers.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_QuestPointer.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Scanner.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Settings.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Signs.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_Utils.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_MapTunerEventHandler.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_MapTunerSettings.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_BacktrackEventHandler.zs"
#include "zscript/mechanics/m8f_hn/m8f_hn_BacktrackSettings.zs"

// Settings ////////////////////////////////////////////////////////////////////
#include "zscript/mechanics/m8f_hn/settings/m8f_hn_bool_setting.zs"
#include "zscript/mechanics/m8f_hn/settings/m8f_hn_cvar_setting.zs"
#include "zscript/mechanics/m8f_hn/settings/m8f_hn_double_setting.zs"
#include "zscript/mechanics/m8f_hn/settings/m8f_hn_int_setting.zs"
#include "zscript/mechanics/m8f_hn/settings/m8f_hn_settings_base.zs"
#include "zscript/mechanics/m8f_hn/settings/m8f_hn_settings_pack.zs"
